version: "3.8"
services:
  mictlanx-router-0:
      image: nachocode/mictlanx:router
      container_name:  mictlanx-router-0
      command: uvicorn mictlanxrouter.server:app --host ${MICTLANX_ROUTER_HOST-0.0.0.0} --port ${MICTLANX_ROUTER_PORT-60666}
      ports:
        - 60666:60666
      environment:
        - LOGGER_NAME=mictlanx-router-0
        - LOG_PATH=/log
        - TEZCANALYTICX_FLUSH_TIMEOUT=10s
        - TEZCANALYTICX_BUFFER_SIZE=100
        - TEZCANALYTICX_PATH=/api/v4/events
        - TEZCANALYTICX_PORT=45000
        - TEZCANALYTICX_HOSTNAME=tezcanalyticx-0
        - TEZCANALYTICX_LEVEL=0
        - TEZCANALYTICX_PROTOCOL=http
        - TEZCANALYTICX_ENABLE=0
        - MICTLANX_PEERS=
        - MICTLANX_PROCOTOL=http
        - MICTLANX_API_VERSION=4
        - MICTLANX_PEER_HEALER_HEARTBEAT=30sec
        - MICTLANX_GC_HEARTBEAT=60sec
        - MICTLANX_SUMMONER_IP_ADDR=mictlanx-xolo-0
        - MICTLANX_SUMMONER_PORT=15000
        - MICTLANX_SUMMONER_MODE=docker
        - MICTLANX_SUMMONER_API_VERSION=3
      volumes:
        - mictlanx-router-0:/log
      networks:
        - mictlanx
      restart: always

  mictlanx-xolo-0:
    image: nachocode/mictlanx:summoner
    container_name: mictlanx-xolo-0
    hostname: mictlanx-xolo-0
    privileged: true
    ports:
      - 15000:15000
    environment:
      - USER_ID=1001
      - GROUP_ID=1002
      - DOCKER_GID=1001
      - BIN_NAME=summoner
      - NODE_ID=mictlanx-xolo-0
      - NODE_PORT=15000
      - IP_ADDRESS=mictlanx-xolo-0
      - SERVER_IP_ADDR=0.0.0.0
      - BASE_PATH=/app/mictlanx
      - LOG_PATH=/app/mictlanx/log
      - LOCAL_PATH=/app/mictlanx/local
      - DATA_PATH=/app/mictlanx/data
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - mictlanx-xolo-0:/app/mictlanx
    networks:
      - mictlanx
     
volumes:
  mictlanx-router-0:
  mictlanx-peer-0:
  mictlanx-peer-1:
  mictlanx-xolo-0:
networks:
  mictlanx:
    external: true


  


